# Generated by Django 4.2.26 on 2025-11-24 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_cache',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['location_key'], name='weather_cac_locatio_ba6874_idx'), models.Index(fields=['expires_at'], name='weather_cac_expires_93b980_idx')],
            },
        ),
    ]
