# Generated by Django 4.2.26 on 2025-11-24 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_district_districts_boundary_gist_idx_and_more'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_chichewa', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=200)),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('min_clay_content', models.FloatField()),
                ('max_clay_content', models.FloatField()),
                ('min_organic_carbon', models.FloatField()),
                ('min_rainfall', models.FloatField()),
                ('max_rainfall', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_elevation', models.FloatField()),
                ('max_elevation', models.FloatField()),
                ('growing_season_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confidence_level', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planting_windows', to='weather.crop')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_windows', to='locations.village')),
            ],
            options={
                'db_table': 'planting_windows',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['village'], name='planting_wi_village_7e5347_idx'), models.Index(fields=['crop'], name='planting_wi_crop_id_10b109_idx'), models.Index(fields=['calculated_at'], name='planting_wi_calcula_13df03_idx')],
            },
        ),
    ]
