# Generated by Django 4.2.26 on 2025-11-24 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_crop_plantingwindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'soil_cache',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['location_key'], name='soil_cache_locatio_3abd0d_idx'), models.Index(fields=['expires_at'], name='soil_cache_expires_e9a59f_idx')],
            },
        ),
    ]
