# Generated by Django 4.2.26 on 2025-11-24 22:21

from django.db import migrations
import uuid


def add_malawian_crops(apps, schema_editor):
    """
    Add common Malawian crops with their soil, climate, and elevation requirements.
    
    Validates: Requirements 3.4, 3.5, 3.6, 7.2, 7.3
    
    Crop data based on agricultural extension guidelines for Malawi.
    """
    Crop = apps.get_model('weather', 'Crop')
    
    crops_data = [
        {
            'name': 'Maize',
            'name_chichewa': 'Chimanga',
            'scientific_name': 'Zea mays',
            # Soil requirements
            'min_ph': 5.5,
            'max_ph': 7.5,
            'min_clay_content': 10.0,
            'max_clay_content': 50.0,
            'min_organic_carbon': 0.5,
            # Climate requirements
            'min_rainfall': 500.0,  # mm per season
            'max_rainfall': 1200.0,
            'min_temperature': 18.0,  # celsius
            'max_temperature': 32.0,
            # Elevation requirements
            'min_elevation': 0.0,  # meters
            'max_elevation': 2400.0,
            'growing_season_days': 120,
        },
        {
            'name': 'Tobacco',
            'name_chichewa': 'Fodya',
            'scientific_name': 'Nicotiana tabacum',
            # Soil requirements
            'min_ph': 5.5,
            'max_ph': 6.5,
            'min_clay_content': 15.0,
            'max_clay_content': 40.0,
            'min_organic_carbon': 1.0,
            # Climate requirements
            'min_rainfall': 600.0,
            'max_rainfall': 1000.0,
            'min_temperature': 20.0,
            'max_temperature': 30.0,
            # Elevation requirements
            'min_elevation': 600.0,
            'max_elevation': 1800.0,
            'growing_season_days': 90,
        },
        {
            'name': 'Groundnuts',
            'name_chichewa': 'Mtedza',
            'scientific_name': 'Arachis hypogaea',
            # Soil requirements
            'min_ph': 5.5,
            'max_ph': 7.0,
            'min_clay_content': 5.0,
            'max_clay_content': 35.0,
            'min_organic_carbon': 0.5,
            # Climate requirements
            'min_rainfall': 500.0,
            'max_rainfall': 1000.0,
            'min_temperature': 20.0,
            'max_temperature': 30.0,
            # Elevation requirements
            'min_elevation': 0.0,
            'max_elevation': 1500.0,
            'growing_season_days': 100,
        },
        {
            'name': 'Beans',
            'name_chichewa': 'Nyemba',
            'scientific_name': 'Phaseolus vulgaris',
            # Soil requirements
            'min_ph': 6.0,
            'max_ph': 7.5,
            'min_clay_content': 10.0,
            'max_clay_content': 40.0,
            'min_organic_carbon': 1.0,
            # Climate requirements
            'min_rainfall': 400.0,
            'max_rainfall': 800.0,
            'min_temperature': 15.0,
            'max_temperature': 28.0,
            # Elevation requirements
            'min_elevation': 0.0,
            'max_elevation': 2000.0,
            'growing_season_days': 75,
        },
        {
            'name': 'Cassava',
            'name_chichewa': 'Chinangwa',
            'scientific_name': 'Manihot esculenta',
            # Soil requirements
            'min_ph': 5.0,
            'max_ph': 7.0,
            'min_clay_content': 5.0,
            'max_clay_content': 45.0,
            'min_organic_carbon': 0.3,
            # Climate requirements
            'min_rainfall': 600.0,
            'max_rainfall': 1500.0,
            'min_temperature': 20.0,
            'max_temperature': 35.0,
            # Elevation requirements
            'min_elevation': 0.0,
            'max_elevation': 1500.0,
            'growing_season_days': 240,
        },
        {
            'name': 'Sweet Potato',
            'name_chichewa': 'Mbatata',
            'scientific_name': 'Ipomoea batatas',
            # Soil requirements
            'min_ph': 5.5,
            'max_ph': 7.0,
            'min_clay_content': 10.0,
            'max_clay_content': 40.0,
            'min_organic_carbon': 0.5,
            # Climate requirements
            'min_rainfall': 500.0,
            'max_rainfall': 1200.0,
            'min_temperature': 20.0,
            'max_temperature': 30.0,
            # Elevation requirements
            'min_elevation': 0.0,
            'max_elevation': 2000.0,
            'growing_season_days': 120,
        },
    ]
    
    for crop_data in crops_data:
        Crop.objects.create(
            id=uuid.uuid4(),
            **crop_data
        )


def remove_malawian_crops(apps, schema_editor):
    """
    Remove the Malawian crops added by this migration.
    """
    Crop = apps.get_model('weather', 'Crop')
    crop_names = ['Maize', 'Tobacco', 'Groundnuts', 'Beans', 'Cassava', 'Sweet Potato']
    Crop.objects.filter(name__in=crop_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_soilcache'),
    ]

    operations = [
        migrations.RunPython(add_malawian_crops, remove_malawian_crops),
    ]
