# Generated by Django 4.2.26 on 2025-11-24 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_chichewa', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_chichewa', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.district')),
            ],
            options={
                'db_table': 'villages',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='districts_name_961bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['name'], name='villages_name_ce20b0_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['district'], name='villages_distric_0f574a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'district')},
        ),
    ]
