# Generated by Django 4.2.26 on 2025-11-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_spatial_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='district',
            name='districts_boundary_gist_idx',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='districts_centroid_gist_idx',
        ),
        migrations.RemoveIndex(
            model_name='village',
            name='villages_location_gist_idx',
        ),
    ]
